package eventbus

// Event types broadcast to connected clients.
const (
	EventTaskCreated                 = "task.created"
	EventTaskUpdated                 = "task.updated"
	EventTaskTransitioned            = "task.transitioned"
	EventTaskAssigned                = "task.assigned"
	EventTaskDispatchBlocked         = "task.dispatch_blocked"
	EventTaskDeleted                 = "task.deleted"
	EventAgentStarted                = "agent.started"
	EventAgentQueued                 = "agent.queued"
	EventAgentQueueCancelled         = "agent.queue.cancelled"
	EventAgentQueuePromoted          = "agent.queue.promoted"
	EventAgentQueueFailed            = "agent.queue.failed"
	EventAgentPoolUpdated            = "agent.pool.updated"
	EventAgentProgress               = "agent.progress"
	EventAgentCompleted              = "agent.completed"
	EventAgentFailed                 = "agent.failed"
	EventAgentOutput                 = "agent.output"
	EventAgentCostUpdate             = "agent.cost_update"
	EventReviewCreated               = "review.created"
	EventReviewCompleted             = "review.completed"
	EventReviewUpdated               = "review.updated"
	EventReviewPendingHuman          = "review.pending_human"
	EventReviewFixRequested          = "review.fix_requested"
	EventNotification                = "notification"
	EventBudgetWarning               = "budget.warning"
	EventBudgetExceeded              = "budget.exceeded"
	EventTaskProgressUpdated         = "task.progress.updated"
	EventTaskProgressAlerted         = "task.progress.alerted"
	EventTaskProgressRecovered       = "task.progress.recovered"
	EventSprintCreated               = "sprint.created"
	EventSprintUpdated               = "sprint.updated"
	EventSprintTransitioned          = "sprint.transitioned"
	EventTaskDependencyResolved      = "task.dependency_resolved"
	EventWorkflowTriggerFired        = "workflow.trigger_fired"
	EventTeamCreated                 = "team.created"
	EventTeamPlanning                = "team.planning"
	EventTeamExecuting               = "team.executing"
	EventTeamReviewing               = "team.reviewing"
	EventTeamCompleted               = "team.completed"
	EventTeamFailed                  = "team.failed"
	EventTeamCancelled               = "team.cancelled"
	EventTeamCostUpdate              = "team.cost_update"
	EventTeamArtifactCreated         = "team.artifact.created"
	EventPluginLifecycle             = "plugin.lifecycle"
	EventSchedulerJobUpdated         = "scheduler.job.updated"
	EventSchedulerRunStarted         = "scheduler.run.started"
	EventSchedulerRunCancelRequested = "scheduler.run.cancel_requested"
	EventSchedulerRunCompleted       = "scheduler.run.completed"
	EventLogCreated                  = "log.created"
	EventWikiPageCreated             = "wiki.page.created"
	EventWikiPageUpdated             = "wiki.page.updated"
	EventWikiPageMoved               = "wiki.page.moved"
	EventWikiPageDeleted             = "wiki.page.deleted"
	EventWikiCommentCreated          = "wiki.comment.created"
	EventWikiCommentResolved         = "wiki.comment.resolved"
	EventWikiVersionPublished        = "wiki.version.published"
	EventLinkCreated                 = "link.created"
	EventLinkDeleted                 = "link.deleted"
	EventTaskCommentCreated          = "task_comment.created"
	EventTaskCommentResolved         = "task_comment.resolved"
	EventAgentPermissionRequest      = "agent.permission_request"
	EventAgentToolCall               = "agent.tool_call"
	EventAgentToolResult             = "agent.tool_result"
	EventAgentReasoning              = "agent.reasoning"
	EventAgentFileChange             = "agent.file_change"
	EventAgentTodoUpdate             = "agent.todo_update"
	EventAgentRateLimit              = "agent.rate_limit"
	EventAgentPartialMessage         = "agent.partial_message"
	EventAgentSnapshot               = "agent.snapshot"

	// Workflow DAG execution events
	EventWorkflowExecutionStarted   = "workflow.execution.started"
	EventWorkflowExecutionAdvanced  = "workflow.execution.advanced"
	EventWorkflowExecutionCompleted = "workflow.execution.completed"
	EventWorkflowExecutionPaused    = "workflow.execution.paused"
	EventWorkflowNodeCompleted      = "workflow.node.completed"
	EventWorkflowNodeWaiting        = "workflow.node.waiting"
	EventWorkflowReviewRequested    = "workflow.review.requested"
	EventWorkflowReviewResolved     = "workflow.review.resolved"
)

// Event types pushed from the TS bridge into Go orchestration.
const (
	BridgeEventOutput            = "output"
	BridgeEventToolCall          = "tool_call"
	BridgeEventToolResult        = "tool_result"
	BridgeEventStatusChange      = "status_change"
	BridgeEventCostUpdate        = "cost_update"
	BridgeEventBudgetAlert       = "budget_alert"
	BridgeEventError             = "error"
	BridgeEventSnapshot          = "snapshot"
	BridgeEventReasoning         = "reasoning"
	BridgeEventFileChange        = "file_change"
	BridgeEventTodoUpdate        = "todo_update"
	BridgeEventProgress          = "progress"
	BridgeEventRateLimit         = "rate_limit"
	BridgeEventPartialMessage    = "partial_message"
	BridgeEventPermissionRequest = "permission_request"
	BridgeEventToolStatusChange  = "tool.status_change"
	BridgeEventToolCallLog       = "tool.call_log"
)

// Protocol/error events introduced by the bus itself.
const (
	EventErrorRejected  = "event.error.rejected"
	EventErrorTransform = "event.error.transform"
)
