// Package qianchuan provides the OAuth state CSRF repository and background
// token refresher for the Qianchuan digital employee (Spec 3 §6.5 + §11).
package qianchuan

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Sentinel errors for OAuth state lookups.
var (
	ErrStateNotFound = errors.New("oauth_state: not found")
	ErrStateExpired  = errors.New("oauth_state: expired")
	ErrStateConsumed = errors.New("oauth_state: already consumed")
)

// OAuthState represents one row in qianchuan_oauth_states.
type OAuthState struct {
	StateToken       uuid.UUID  `gorm:"column:state_token;primaryKey"`
	ProjectID        uuid.UUID  `gorm:"column:project_id"`
	RedirectURI      string     `gorm:"column:redirect_uri"`
	InitiatedBy      uuid.UUID  `gorm:"column:initiated_by"`
	DisplayName      *string    `gorm:"column:display_name"`
	ActingEmployeeID *uuid.UUID `gorm:"column:acting_employee_id"`
	ExpiresAt        time.Time  `gorm:"column:expires_at"`
	ConsumedAt       *time.Time `gorm:"column:consumed_at"`
	CreatedAt        time.Time  `gorm:"column:created_at"`
}

func (OAuthState) TableName() string { return "qianchuan_oauth_states" }

// OAuthStateRepo implements CRUD + lifecycle queries for oauth states.
type OAuthStateRepo struct{ db *gorm.DB }

// NewOAuthStateRepo wires the repository.
func NewOAuthStateRepo(db *gorm.DB) *OAuthStateRepo { return &OAuthStateRepo{db: db} }

// Create inserts a new OAuth state row. StateToken is generated by the DB
// default if left at uuid.Nil; callers may pre-generate for test control.
func (r *OAuthStateRepo) Create(ctx context.Context, s *OAuthState) error {
	if s.StateToken == uuid.Nil {
		s.StateToken = uuid.New()
	}
	return r.db.WithContext(ctx).Create(s).Error
}

// Lookup fetches by state_token and enforces expiry + single-use semantics.
func (r *OAuthStateRepo) Lookup(ctx context.Context, token uuid.UUID) (*OAuthState, error) {
	var row OAuthState
	if err := r.db.WithContext(ctx).Where("state_token = ?", token).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrStateNotFound
		}
		return nil, err
	}
	if row.ConsumedAt != nil {
		return nil, ErrStateConsumed
	}
	if time.Now().UTC().After(row.ExpiresAt) {
		return nil, ErrStateExpired
	}
	return &row, nil
}

// MarkConsumed atomically sets consumed_at if not already consumed.
func (r *OAuthStateRepo) MarkConsumed(ctx context.Context, token uuid.UUID) error {
	now := time.Now().UTC()
	res := r.db.WithContext(ctx).
		Model(&OAuthState{}).
		Where("state_token = ? AND consumed_at IS NULL", token).
		Update("consumed_at", now)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return ErrStateConsumed
	}
	return nil
}

// DeleteExpired removes all rows whose expires_at is before the given time.
// Returns the number of deleted rows.
func (r *OAuthStateRepo) DeleteExpired(ctx context.Context, before time.Time) (int64, error) {
	res := r.db.WithContext(ctx).
		Where("expires_at < ?", before).
		Delete(&OAuthState{})
	return res.RowsAffected, res.Error
}
